version: '3.7'

services:
  django:
    container_name: jenkins      
    build:
      context: ./
      dockerfile: Dockerfile
    image: django-jenkins
    ports:
      - 8080:8080
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
